# -*- coding: utf-8 -*-
"""morales_cocoa_recomendador_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSN0Ex0C_WjxxzV405JcWeBpQY0ESdKj

# 🍫 Morales Cocoa — Sistema de Recomendación de Producto
**Modelos:** KNN + ANN (Keras) | **Dataset:** Sintético
"""

import numpy as np
import pandas as pd
import random
import warnings
warnings.filterwarnings("ignore")

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix,
    accuracy_score, ConfusionMatrixDisplay
)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

print("TF:", tf.__version__, "| OK ✓")

"""## 1. Catálogo de productos"""

PRODUCTS = {
    0:  ("55% Leche - Almendra",     "leche",  "frutos_secos", 55),
    1:  ("55% Leche - Canela",       "leche",  "especias",     55),
    2:  ("55% Leche - Hierba Luisa", "leche",  "herbal",       55),
    3:  ("55% Leche - Maracuyá",     "leche",  "tropical",     55),
    4:  ("55% Leche - Menta",        "leche",  "mentolado",    55),
    5:  ("55% Leche - Naranja",      "leche",  "cítrico",      55),
    6:  ("75% Oscuro - Almendra",    "oscuro", "frutos_secos", 75),
    7:  ("75% Oscuro - Canela",      "oscuro", "especias",     75),
    8:  ("75% Oscuro - Hierba Luisa","oscuro", "herbal",       75),
    9:  ("75% Oscuro - Menta",       "oscuro", "mentolado",    75),
}

FLAVORS    = ["frutos_secos", "especias", "herbal", "tropical", "mentolado", "cítrico"]
CATEGORIES = ["leche", "oscuro"]

for pid, (name, cat, flavor, cacao) in PRODUCTS.items():
    print(f"[{pid}] {name}")

"""## 2. Generación de datos sintéticos

**Features:**
- `cat_preference` — 0=leche, 1=oscuro (filtro usado en catálogo)
- `flavor_preference` — 0-5 (sabor más clickeado)
- `items_in_cart` — cantidad de barras distintas en carrito
- `subtotal` — monto acumulado en USD
- `time_on_catalog_s` — segundos en página de catálogo
- `viewed_detail` — 1 si abrió detalle de producto
- `cacao_avg_cart` — promedio % cacao de los items en carrito

**Target:** `recommended_product` — id del producto comprado (0-9)
"""

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
N_SAMPLES = 8000

def generate_session(n=N_SAMPLES):
    rows = []
    for _ in range(n):
        cat_pref = 0 if random.random() < 0.60 else 1

        # Preferencia de sabor correlacionada con la categoría
        if cat_pref == 0:   # leche → más tropical/cítrico
            flavor_pref = random.choices(range(6),
                weights=[0.15, 0.10, 0.10, 0.35, 0.15, 0.15])[0]
        else:               # oscuro → más especias/herbal
            flavor_pref = random.choices(range(6),
                weights=[0.20, 0.30, 0.25, 0.05, 0.15, 0.05])[0]

        items_in_cart   = random.randint(0, 8)
        subtotal        = max(0.0, round(items_in_cart * 2.50 + random.uniform(-0.5, 2.0), 2))
        time_on_catalog = random.randint(10, 300)
        viewed_detail   = random.randint(0, 1)
        cacao_avg       = round((55 if cat_pref == 0 else 75) + random.uniform(-5, 5), 1)

        # Target: producto comprado (con peso al que coincide en categoría + sabor)
        cat_name    = CATEGORIES[cat_pref]
        flavor_name = FLAVORS[flavor_pref]
        candidates  = [pid for pid, (_, c, _, _) in PRODUCTS.items() if c == cat_name]
        weights     = [0.70 if PRODUCTS[pid][2] == flavor_name
                       else 0.30 / (len(candidates) - 1)
                       for pid in candidates]
        total_w     = sum(weights)
        weights     = [w / total_w for w in weights]
        target      = random.choices(candidates, weights=weights)[0]

        rows.append({
            "cat_preference":      cat_pref,
            "flavor_preference":   flavor_pref,
            "items_in_cart":       items_in_cart,
            "subtotal":            subtotal,
            "time_on_catalog_s":   time_on_catalog,
            "viewed_detail":       viewed_detail,
            "cacao_avg_cart":      cacao_avg,
            "recommended_product": target
        })
    return pd.DataFrame(rows)

df = generate_session()
print(f"Dataset: {df.shape[0]} filas × {df.shape[1]} columnas")
df.head()

"""## 3. Preprocesamiento"""

X = df.drop("recommended_product", axis=1)
Y = df["recommended_product"]

scaler  = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(
    X_scaled, Y, test_size=0.20, random_state=SEED, stratify=Y
)

print(f"Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")
print(f"Clases: {sorted(Y.unique())}")

"""## 4. Modelo 1 — KNN"""

k_range  = range(1, 21)
k_scores = []
for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k, metric="euclidean")
    knn.fit(X_train, Y_train)
    k_scores.append(accuracy_score(Y_test, knn.predict(X_test)))

best_k = list(k_range)[np.argmax(k_scores)]
print(f"Mejor K = {best_k}  →  Accuracy = {max(k_scores):.4f}")

plt.figure(figsize=(7, 3))
plt.plot(list(k_range), k_scores, marker="o", color="#C8A86B")
plt.axvline(best_k, linestyle="--", color="#4A2E1A", label=f"K={best_k}")
plt.xlabel("K"); plt.ylabel("Accuracy")
plt.title("Accuracy vs K")
plt.legend(); plt.tight_layout(); plt.show()

knn_best = KNeighborsClassifier(n_neighbors=best_k, metric="euclidean")
knn_best.fit(X_train, Y_train)
knn_pred = knn_best.predict(X_test)

print(classification_report(Y_test, knn_pred,
      target_names=[PRODUCTS[i][0] for i in sorted(Y.unique())]))

fig, ax = plt.subplots(figsize=(10, 8))
ConfusionMatrixDisplay(
    confusion_matrix(Y_test, knn_pred),
    display_labels=[PRODUCTS[i][0] for i in sorted(Y.unique())]
).plot(ax=ax, cmap="YlOrBr", xticks_rotation=45)
ax.set_title("Matriz de Confusión — KNN")
plt.tight_layout(); plt.show()

"""## 5. Modelo 2 — ANN (Keras)"""

n_classes  = len(Y.unique())
n_features = X_train.shape[1]

ann = Sequential([
    Dense(64, activation="relu", input_shape=(n_features,)),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dropout(0.2),
    Dense(16, activation="relu"),
    Dense(n_classes, activation="softmax")
])
ann.compile(optimizer="adam",
            loss="sparse_categorical_crossentropy",
            metrics=["accuracy"])
ann.summary()

history = ann.fit(
    X_train, Y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.15,
    callbacks=[EarlyStopping(monitor="val_loss", patience=10,
                             restore_best_weights=True)],
    verbose=1
)

loss_df = pd.DataFrame(history.history)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
sns.lineplot(data=loss_df[["loss", "val_loss"]], ax=axes[0])
axes[0].set_title("Loss"); axes[0].set_xlabel("Época")

sns.lineplot(data=loss_df[["accuracy", "val_accuracy"]], ax=axes[1])
axes[1].set_title("Accuracy"); axes[1].set_xlabel("Época")

plt.tight_layout(); plt.show()

ann_pred = np.argmax(ann.predict(X_test), axis=1)

print(classification_report(Y_test, ann_pred,
      target_names=[PRODUCTS[i][0] for i in sorted(Y.unique())]))

fig, ax = plt.subplots(figsize=(10, 8))
ConfusionMatrixDisplay(
    confusion_matrix(Y_test, ann_pred),
    display_labels=[PRODUCTS[i][0] for i in sorted(Y.unique())]
).plot(ax=ax, cmap="YlOrBr", xticks_rotation=45)
ax.set_title("Matriz de Confusión — ANN")
plt.tight_layout(); plt.show()

"""## 6. Comparativa KNN vs ANN"""

acc_knn = accuracy_score(Y_test, knn_pred)
acc_ann = accuracy_score(Y_test, ann_pred)

results = pd.DataFrame({
    "Modelo":   [f"KNN (K={best_k})", "ANN (Keras)"],
    "Accuracy": [round(acc_knn, 4), round(acc_ann, 4)]
})
print(results.to_string(index=False))

plt.figure(figsize=(5, 3))
sns.barplot(data=results, x="Modelo", y="Accuracy",
            palette=["#C8A86B", "#4A2E1A"])
plt.ylim(0, 1)
plt.title("Accuracy — KNN vs ANN")
plt.tight_layout(); plt.show()

"""## 7. Demo — función de recomendación"""

def recomendar(cat_preference, flavor_preference, items_in_cart,
               subtotal, time_on_catalog_s, viewed_detail, cacao_avg_cart,
               top_n=3):
    row = pd.DataFrame([[cat_preference, flavor_preference, items_in_cart,
                         subtotal, time_on_catalog_s, viewed_detail, cacao_avg_cart]],
                       columns=X.columns)
    probs       = ann.predict(scaler.transform(row), verbose=0)[0]
    top_indices = np.argsort(probs)[::-1][:top_n]

    print(f"Preferencia: {'Leche 55%' if cat_preference==0 else 'Oscuro 75%'}"
          f" | Sabor: {FLAVORS[flavor_preference]}"
          f" | Carrito: {items_in_cart} items (${subtotal:.2f})")
    print()
    for rank, pid in enumerate(top_indices, 1):
        bar = "█" * int(probs[pid] * 30)
        print(f"  #{rank}  {PRODUCTS[pid][0]:<35}  {probs[pid]:.1%}  {bar}")

# Ejemplo 1 — leche + tropical
print("── Ejemplo 1 ──────────────────────────────")
recomendar(0, 3, 2, 5.00, 90, 1, 55.0)

# Ejemplo 2 — oscuro + especias
print("
── Ejemplo 2 ──────────────────────────────")
recomendar(1, 1, 4, 10.00, 200, 1, 75.0)

# Ejemplo 3 — cold start
print("
── Ejemplo 3 (cold start) ─────────────────")
recomendar(0, 5, 0, 0.0, 15, 0, 55.0)